#include<stdio.h>


// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

int Fibonacci(){

    int num1 = 1, num2 = 1, temp;
    int total = 0;


    while(num2 <= 4000000) {
        if(num1 % 2 == 0) {
            total += num1;
        }

        temp = num1;
        num1 = num2;
        num2 = num1 + temp;
    }

    return total;

}


int main(){

    int retval;
    retval = Fibonacci();
    printf("Total : %d\n", retval);
}